// @ts-nocheck
import assert from 'node:assert/strict';
for(const extension of ['.mp3','.png','.jpg','.jpeg','.webp'])require.extensions[extension]=(module:NodeModule,filename:string)=>{module.exports=filename;};
process.env.EXPO_PUBLIC_APP_ENV='preview';process.env.EXPO_PUBLIC_EGYPTIAN_UNIT1_CURRICULUM_VERSION='v2';process.env.EXPO_PUBLIC_EGYPTIAN_UNIT2_CURRICULUM_VERSION='v2';
const {buildEgyptianUnit1CurriculumUnit,buildEgyptianUnit2CurriculumUnit,resolveEgyptianUnit2CurriculumVersion}=require('../data/curriculum/egyptian');const {buildMsaUnit2CurriculumUnit}=require('../data/curriculum/msa');const {buildGulfUnit2CurriculumUnit}=require('../data/curriculum/gulf');const {getDialectContent}=require('../data/content-registry');const {resolveCurriculumItem,getDialectContentMeta}=require('../utils/content-resolver');const {buildEgyptianUnit2BigReviewQuestions,buildEgyptianUnit2ChallengeQuestions}=require('../data/egyptian-unit2-quizzes');const {getQuizPassedAtThreshold}=require('../utils/quiz-scoring');
const ids=['around_the_home','where_are_my_things','simple_actions_at_home','getting_dressed','today_now_later','ready_or_missing','what_do_you_like','helping_at_home','leaving_and_coming_back','put_the_steps_together','big_review','getting_ready_with_yusuf','first_short_sentence_challenge'];const unit=buildEgyptianUnit2CurriculumUnit('v2');const content=getDialectContent('egyptian');assert.equal(unit.title,'Build Short Sentences');assert.equal(unit.subtitle,'Combine words for everyday life at home.');assert.deepEqual(unit.items.map(item=>item.missionId),ids);assert.equal(new Set(ids).size,13);const resolved=unit.items.map(item=>resolveCurriculumItem(item,content));assert.ok(resolved.every(Boolean));
resolved.slice(0,10).forEach(entry=>{assert.equal(entry.lessonWords.length,24);assert.equal(entry.missionContent.audioMode,'default');assert.equal(entry.missionContent.pronunciationEnabled,true);entry.lessonWords.forEach(word=>{assert.ok(word.arabic&&word.transliteration&&word.english);assert.equal(word.evalTarget,word.displayArabic);});});resolved.slice(10).forEach((entry,index)=>{assert.equal(entry.missionContent.audioMode,index===1?'default':'none');assert.notEqual(entry.missionContent.pronunciationEnabled,true);});
const words=resolved.slice(0,10).flatMap(entry=>entry.lessonWords);assert.ok(words.some(word=>word.arabic==='نظارة'&&word.transliteration==='naḍḍaara'));assert.ok(words.some(word=>word.arabic==='نظارتي'&&word.transliteration==='naḍḍaarati'));assert.ok(words.some(word=>word.arabic.startsWith('النظارة ')&&word.transliteration.startsWith('in-naḍḍaara ')));assert.equal(words.some(word=>/نضار/.test(word.arabic)),false);assert.ok(words.some(word=>word.arabic==='ماشي، هلبسه'&&word.transliteration==='maashi, halbasu'));assert.ok(words.filter(word=>word.arabic.includes('بالليل')).every(word=>/night/i.test(word.english)&&!/evening/i.test(word.english)));
const review=buildEgyptianUnit2BigReviewQuestions('audit-review');const challenge=buildEgyptianUnit2ChallengeQuestions('audit-challenge');assert.equal(review.length,24);assert.equal(resolved[11].dialogue.length,24);assert.equal(challenge.length,20);for(const category of ['mini_situation','best_reply','phrase_arrangement','translation','mixed_situation'])assert.equal(challenge.filter(question=>question.category===category).length,4);assert.equal(review.some(question=>challenge.some(other=>other.id===question.id)),false);assert.ok(challenge.every(question=>question.hideTransliterationBeforeAnswer&&question.format!=='listening'&&question.format!=='scene_replay'));assert.equal(getQuizPassedAtThreshold(15,20,16),false);assert.equal(getQuizPassedAtThreshold(16,20,16),true);
for(const bank of [review,challenge]){const positions=bank.filter(question=>'options'in question).map(question=>question.options.findIndex(option=>option.isCorrect));let streak=1;for(let i=1;i<positions.length;i++){streak=positions[i]===positions[i-1]?streak+1:1;assert.ok(streak<=2);}for(const question of bank)if('options'in question){assert.equal(question.options.filter(option=>option.isCorrect).length,1);const labels=question.options.map(option=>'arabic'in option?option.arabic:option.meaning);assert.equal(new Set(labels).size,labels.length);}}
const unit1=buildEgyptianUnit1CurriculumUnit('v2');assert.equal(getDialectContentMeta('egyptian','big_review','quiz','unit-1').unitId,'unit-1');assert.equal(getDialectContentMeta('egyptian','big_review','quiz','unit-2').unitId,'unit-2');assert.notEqual(resolveCurriculumItem(unit1.items.find(item=>item.missionId==='big_review'),content).missionContent,resolved[10].missionContent);assert.equal(buildEgyptianUnit2CurriculumUnit('legacy').items.filter(item=>item.contentType==='scenario').length,8);assert.equal(resolveEgyptianUnit2CurriculumVersion({requestedVersion:'v2',appEnv:'production',isLocalDevelopment:true}),'legacy');
const msa=resolveCurriculumItem(buildMsaUnit2CurriculumUnit('v2').items[0],getDialectContent('msa')).lessonWords[1];const gulf=resolveCurriculumItem(buildGulfUnit2CurriculumUnit('v2').items[0],getDialectContent('gulf')).lessonWords[1];assert.notEqual(msa.transliteration,resolved[0].lessonWords[1].transliteration);assert.notEqual(gulf.transliteration,resolved[0].lessonWords[1].transliteration);
console.log('Egyptian Unit 2 v2 audit passed: 13 missions, 240 lesson items, 24 review questions, 24 dialogue turns, 20 challenge questions.');
