import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import { buildUnit1_2AudioManifest } from './lib/unit1-2-audio-plan';

const OUTPUT_PATH = resolve(process.cwd(), 'constants/audio-v2-registry.ts');

export function renderUnit1_2AudioRegistry() {
  const manifest = buildUnit1_2AudioManifest();
  const uniqueEntries = manifest.filter(entry => entry.reuseSource === null);
  const lines = [
    '/* This file is generated by scripts/generate-unit1-2-audio-registry.ts. */',
    '/* Do not edit manually. Metro needs each literal module reference below. */',
    "import type { SupportedDialect } from '../data/curriculum/types';",
    '',
    'export type V2AudioModule = number;',
    '',
    'export const V2_AUDIO_REGISTRY: Record<SupportedDialect, Readonly<Record<string, V2AudioModule>>> = {',
  ];

  for (const dialect of ['msa', 'gulf', 'egyptian'] as const) {
    lines.push(`  ${dialect}: {`);
    for (const entry of uniqueEntries.filter(candidate => candidate.dialect === dialect)) {
      lines.push(`    '${entry.audioKey}': require('../${entry.intendedOutputPath}'),`);
    }
    lines.push('  },');
  }

  lines.push(
    '};',
    '',
    'export const V2_AUDIO_REFERENCE_KEYS: Readonly<Record<string, string>> = {',
  );
  for (const entry of manifest) {
    lines.push(`  '${entry.referenceId}': '${entry.audioKey}',`);
  }
  lines.push('};');
  return `${lines.join('\n')}\n`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const rendered = renderUnit1_2AudioRegistry();
  const checkOnly = process.argv.includes('--check');
  if (checkOnly) {
    if (!existsSync(OUTPUT_PATH) || readFileSync(OUTPUT_PATH, 'utf8') !== rendered) {
      console.error('constants/audio-v2-registry.ts is not deterministic or is out of date.');
      process.exitCode = 1;
    } else {
      console.log('Unit 1/2 v2 audio registry is deterministic and current.');
    }
  } else {
    writeFileSync(OUTPUT_PATH, rendered);
    console.log(`Wrote ${OUTPUT_PATH}`);
  }
}
